
# Configuration dev local

spring:
  application:
    name: customer-api

  datasource:
    driver-class-name: org.postgresql.Driver
    # url, username and password defined on application-local.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration

  config:
    import: optional:application-local.yml  # local file with credentials

logging:
  level:
    org.flyway: DEBUG


# JWT Configuration

jwt:
  secret: MinhaChaveSuperSecreta123456abcde
  expiration: 3600000  # 1 hora em milissegundos
